SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "JavaScript",
    "HTML",
    "CSS",
    "SQL",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "React",
    "Angular",
    "Node.js",
    "Express.js",
    "FastAPI",
    "Flask",
    "Django",
    "Spring Boot",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Data Science",
    "Data Analytics",
    "Power BI",
    "Tableau",
    "Excel",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "Azure",
    "Linux",
    "TensorFlow",
    "PyTorch",
    "spaCy",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn"
]
