"""Skills dictionary for resume and job description matching."""

SKILLS = {
    "Programming Languages": [
        "Python",
        "Java",
        "C",
        "C++",
        "C#",
        "JavaScript",
        "TypeScript",
        "Go",
        "Rust",
        "Ruby",
        "PHP",
        "Swift",
        "Kotlin",
        "R",
        "Scala",
    ],
    "Frontend Development": [
        "React",
        "Vue.js",
        "Angular",
        "Svelte",
        "Next.js",
        "HTML",
        "CSS",
        "SASS",
        "Bootstrap",
        "Tailwind CSS",
        "jQuery",
    ],
    "Backend Development": [
        "Node.js",
        "Express.js",
        "FastAPI",
        "Flask",
        "Django",
        "Spring Boot",
        "Spring",
        "ASP.NET",
        "Ruby on Rails",
        "Laravel",
        "Nest.js",
    ],
    "Databases": [
        "SQL",
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "Oracle",
        "SQLite",
        "Redis",
        "Elasticsearch",
    ],
    "Data Science & ML": [
        "Machine Learning",
        "Deep Learning",
        "Artificial Intelligence",
        "Data Science",
        "Data Analytics",
        "TensorFlow",
        "PyTorch",
        "scikit-learn",
        "spaCy",
        "NLTK",
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Seaborn",
        "Plotly",
        "Keras",
    ],
    "Cloud & DevOps": [
        "AWS",
        "Azure",
        "Google Cloud",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "GitHub Actions",
        "Terraform",
        "Ansible",
    ],
    "Tools & Platforms": [
        "Git",
        "GitHub",
        "GitLab",
        "Linux",
        "Windows",
        "Unix",
        "Jira",
        "Confluence",
        "Postman",
    ],
    "Visualization & BI": [
        "Power BI",
        "Tableau",
        "Excel",
        "Looker",
        "Google Analytics",
    ],
    "Testing & QA": [
        "Selenium",
        "pytest",
        "Jest",
        "Cypress",
        "Manual Testing",
        "Automation Testing",
    ],
    "Other Skills": [
        "REST API",
        "GraphQL",
        "Microservices",
        "System Design",
        "Agile",
        "Scrum",
        "Kanban",
    ],
}

FLAT_SKILLS = []
for category_skills in SKILLS.values():
    FLAT_SKILLS.extend(category_skills)

FLAT_SKILLS = list(dict.fromkeys(FLAT_SKILLS))
FLAT_SKILLS.sort()
